# Generated by Django 3.2.7 on 2021-11-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211027_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
